export const pricesDemo = [
   {
     "ItemCode": "7290002133612",
     "AllowDiscount": "1",
     "ItemId": "1011077",
     "ItemName": "יוגורט יווני אותנטי",
     "ItemPrice": "6.40",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "יוגורט יווני אותנטי",
     "ManufacturerName": "מחלבת השומרון",
     "PriceUpdateDate": "2023-08-13 08:40:34",
     "QtyInPackage": "לא ידוע",
     "Quantity": "180.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0356",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290002133643",
     "AllowDiscount": "1",
     "ItemId": "1011080",
     "ItemName": "גבינת פטה צאן 22% גב",
     "ItemPrice": "24.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "גבינת פטה צאן 22% גב",
     "ManufacturerName": "מחלבת השומרון",
     "PriceUpdateDate": "2023-06-01 08:51:38",
     "QtyInPackage": "לא ידוע",
     "Quantity": "200.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.1245",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290002133858",
     "AllowDiscount": "1",
     "ItemId": "1011085",
     "ItemName": "גבינה בולגרית צאן 18",
     "ItemPrice": "24.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "גבינה בולגרית צאן 18",
     "ManufacturerName": "מחלבת השומרון",
     "PriceUpdateDate": "2023-06-01 08:51:38",
     "QtyInPackage": "לא ידוע",
     "Quantity": "250.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0996",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290002133889",
     "AllowDiscount": "1",
     "ItemId": "1011086",
     "ItemName": "גבינה בולגרית מעודנת",
     "ItemPrice": "24.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "גבינה בולגרית מעודנת",
     "ManufacturerName": "מחלבת השומרון",
     "PriceUpdateDate": "2023-06-01 08:51:38",
     "QtyInPackage": "לא ידוע",
     "Quantity": "250.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0996",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290013771216",
     "AllowDiscount": "1",
     "ItemId": "1011092",
     "ItemName": "פטאקי 16% גבינות השו",
     "ItemPrice": "16.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פטאקי 16% גבינות השו",
     "ManufacturerName": "מחלבת השומרון",
     "PriceUpdateDate": "2023-08-13 08:40:34",
     "QtyInPackage": "לא ידוע",
     "Quantity": "250.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0676",
     "UnitQty": "גרמים",
     "bIsWeighted": "0",
     "PromotionId": "1309308",
     "PromotionDescription": "גבינה יוונית פטאקי 16% ב12.90",
     "PromotionUpdateDate": "2023-08-23 00:00",
     "PromotionStartDate": "2023-08-13",
     "PromotionMinQty": "1.00",
     "PromotionDiscountedPrice": "12.90",
     "PromotionDiscountedPricePerMida": "12.90",
     "PromotionMinNoOfItemOfered": "10",
     "PromotionWeightUnit": "1",
     "PromotionDiscountRate": "",
     "PromotionItemCode": [
       "7290013771216"
     ]
   },
   {
     "ItemCode": "7290108357196",
     "AllowDiscount": "1",
     "ItemId": "6481801",
     "ItemName": "מתז לניקוי כללי ג'ט+",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מתז לניקוי כללי ג'ט+",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2021-12-24 06:22:03",
     "QtyInPackage": "לא ידוע",
     "Quantity": "750.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0159",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290110558420",
     "AllowDiscount": "1",
     "ItemId": "6621208",
     "ItemName": "אלפרו משקה שיבולת שו",
     "ItemPrice": "12.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אלפרו משקה שיבולת שו",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-11-17 12:39:12",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "12.9000",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7509546666846",
     "AllowDiscount": "1",
     "ItemId": "6479832",
     "ItemName": "קולגייט טוטאל פחם מש",
     "ItemPrice": "19.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קולגייט טוטאל פחם מש",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2021-05-26 11:01:47",
     "QtyInPackage": "לא ידוע",
     "Quantity": "75.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.2653",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290002814368",
     "AllowDiscount": "1",
     "ItemId": "6433572",
     "ItemName": "מסיר שומנים קר מתז 8",
     "ItemPrice": "13.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מסיר שומנים קר מתז 8",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2020-10-11 18:47:22",
     "QtyInPackage": "לא ידוע",
     "Quantity": "800.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0174",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0",
     "PromotionId": "1309446",
     "PromotionDescription": "מסיר שומנים 800 מל 9.90",
     "PromotionUpdateDate": "2023-08-10 00:00",
     "PromotionStartDate": "2023-08-10",
     "PromotionMinQty": "1.00",
     "PromotionDiscountedPrice": "9.90",
     "PromotionDiscountedPricePerMida": "9.90",
     "PromotionMinNoOfItemOfered": "10",
     "PromotionWeightUnit": "1",
     "PromotionDiscountRate": "",
     "PromotionItemCode": [
       "7290002814368"
     ]
   },
   {
     "ItemCode": "7290006805379",
     "AllowDiscount": "1",
     "ItemId": "6204644",
     "ItemName": "שליש בגט",
     "ItemPrice": "2.40",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "שליש בגט",
     "ManufacturerName": "פילסברי",
     "PriceUpdateDate": "2023-04-12 20:12:21",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "2.4000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290102399048",
     "AllowDiscount": "1",
     "ItemId": "5583447",
     "ItemName": "קשקבל נעם 200 גר",
     "ItemPrice": "24.50",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קשקבל נעם 200 גר",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-06 15:37:41",
     "QtyInPackage": "לא ידוע",
     "Quantity": "200.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.1225",
     "UnitQty": "גרמים",
     "bIsWeighted": "0",
     "PromotionId": "1309078",
     "PromotionDescription": "קשקבל פרוסות נעם19.90",
     "PromotionUpdateDate": "2023-08-08 00:00",
     "PromotionStartDate": "2023-08-13",
     "PromotionMinQty": "1.00",
     "PromotionDiscountedPrice": "19.90",
     "PromotionDiscountedPricePerMida": "19.90",
     "PromotionMinNoOfItemOfered": "10",
     "PromotionWeightUnit": "1",
     "PromotionDiscountRate": "",
     "PromotionItemCode": [
       "7290102399048"
     ]
   },
   {
     "ItemCode": "7290110324070",
     "AllowDiscount": "1",
     "ItemId": "5460738",
     "ItemName": "גבינת חלומי מחלב בקר",
     "ItemPrice": "18.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "גבינת חלומי מחלב בקר",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-08 20:44:31",
     "QtyInPackage": "לא ידוע",
     "Quantity": "200.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0945",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290017065007",
     "AllowDiscount": "1",
     "ItemId": "2831499",
     "ItemName": "מוצרלה פרוסה גד 150",
     "ItemPrice": "18.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מוצרלה פרוסה גד 150",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-05 10:44:51",
     "QtyInPackage": "לא ידוע",
     "Quantity": "150.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.1253",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "8435495805199",
     "AllowDiscount": "1",
     "ItemId": "4591395",
     "ItemName": "אבקת כביסה תינוקלין",
     "ItemPrice": "39.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אבקת כביסה תינוקלין",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2020-07-05 12:46:56",
     "QtyInPackage": "לא ידוע",
     "Quantity": "3.00",
     "UnitOfMeasure": "ק\"ג     ",
     "UnitOfMeasurePrice": "13.3000",
     "UnitQty": "קילוגרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290011276485",
     "AllowDiscount": "1",
     "ItemId": "2268136",
     "ItemName": "חסה עגולה רמי לוי",
     "ItemPrice": "5.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "חסה עגולה רמי לוי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-15 13:28:23",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "5.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290019302643",
     "AllowDiscount": "1",
     "ItemId": "6704534",
     "ItemName": "יין תפוח באזז יקבי כ",
     "ItemPrice": "26.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "יין תפוח באזז יקבי כ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-30 11:04:05",
     "QtyInPackage": "לא ידוע",
     "Quantity": "750.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0359",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290016132106",
     "AllowDiscount": "1",
     "ItemId": "3387268",
     "ItemName": "כיסא פלסטיק איכותי",
     "ItemPrice": "19.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "כיסא פלסטיק איכותי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2017-09-11 09:45:15",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "19.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018098769",
     "AllowDiscount": "1",
     "ItemId": "6636651",
     "ItemName": "פרישייק פירות מנגו ב",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פרישייק פירות מנגו ב",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-12-29 14:28:30",
     "QtyInPackage": "לא ידוע",
     "Quantity": "300.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0397",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290112190420",
     "AllowDiscount": "1",
     "ItemId": "4275422",
     "ItemName": "פופקורן מתוק 80ג רמי",
     "ItemPrice": "3.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פופקורן מתוק 80ג רמי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:20:10",
     "QtyInPackage": "לא ידוע",
     "Quantity": "80.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0487",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290000735203",
     "AllowDiscount": "1",
     "ItemId": "4136413",
     "ItemName": "ענב אדום ארוז 500 גר",
     "ItemPrice": "14.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "ענב אדום ארוז 500 גר",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-04-15 07:32:48",
     "QtyInPackage": "לא ידוע",
     "Quantity": "500.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0298",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290006644527",
     "AllowDiscount": "1",
     "ItemId": "3702969",
     "ItemName": "תפוזינה תות בננה 0.5",
     "ItemPrice": "4.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "תפוזינה תות בננה 0.5",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-11 15:20:09",
     "QtyInPackage": "לא ידוע",
     "Quantity": "500.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0098",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290017023212",
     "AllowDiscount": "1",
     "ItemId": "4107574",
     "ItemName": "שוופס רביעייה מוגז פ",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "שוופס רביעייה מוגז פ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-02-10 06:16:12",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.32",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "9.0152",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290017023229",
     "AllowDiscount": "1",
     "ItemId": "4107575",
     "ItemName": "שוופס רביעייה מוגז פ",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "שוופס רביעייה מוגז פ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-01-14 09:23:48",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.32",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "9.0152",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290017023236",
     "AllowDiscount": "1",
     "ItemId": "4107576",
     "ItemName": "שוופס רביעייה מוגז פ",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "שוופס רביעייה מוגז פ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-01-14 09:23:48",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.32",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "9.0152",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0",
     "PromotionId": "1311514",
     "PromotionDescription": "רביעיית שוופס 11.50 כולל",
     "PromotionUpdateDate": "2023-09-03 00:00",
     "PromotionStartDate": "2023-09-03",
     "PromotionMinQty": "1.00",
     "PromotionDiscountedPrice": "11.50",
     "PromotionDiscountedPricePerMida": "10.30",
     "PromotionMinNoOfItemOfered": "10",
     "PromotionWeightUnit": "1",
     "PromotionDiscountRate": "",
     "PromotionItemCode": [
       "7290017023236"
     ]
   },
   {
     "ItemCode": "7290016509304",
     "AllowDiscount": "1",
     "ItemId": "2994380",
     "ItemName": "סוד כדוריות סבון נתל",
     "ItemPrice": "7.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "סוד כדוריות סבון נתל",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2020-06-11 09:47:39",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "7.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290006765000",
     "AllowDiscount": "1",
     "ItemId": "4740069",
     "ItemName": "טורטיה 12 יח קמח מלא",
     "ItemPrice": "9.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "טורטיה 12 יח קמח מלא",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:16:54",
     "QtyInPackage": "לא ידוע",
     "Quantity": "540.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0183",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "4022025261002",
     "AllowDiscount": "1",
     "ItemId": "3070302",
     "ItemName": "בלו וויין 750 מ\"ל",
     "ItemPrice": "44.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "בלו וויין 750 מ\"ל",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-09-07 12:30:04",
     "QtyInPackage": "לא ידוע",
     "Quantity": "750.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0599",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7296168017193",
     "AllowDiscount": "1",
     "ItemId": "3826058",
     "ItemName": "פלסטר שקוף 30יח",
     "ItemPrice": "6.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פלסטר שקוף 30יח",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2017-12-17 09:32:34",
     "QtyInPackage": "לא ידוע",
     "Quantity": "30.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "0.2300",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290108272895",
     "AllowDiscount": "1",
     "ItemId": "3552622",
     "ItemName": "סבון ידיים 3*500 מ\"ל",
     "ItemPrice": "9.60",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "סבון ידיים 3*500 מ\"ל",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-12-11 14:21:13",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.50",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "6.4000",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290013608482",
     "AllowDiscount": "1",
     "ItemId": "2443872",
     "ItemName": "פרימור נקטר מנגו 1לי",
     "ItemPrice": "5.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פרימור נקטר מנגו 1לי",
     "ManufacturerName": "דיפלומט",
     "PriceUpdateDate": "2023-03-31 08:35:08",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "5.9000",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3600521094341",
     "AllowDiscount": "1",
     "ItemId": "1011438",
     "ItemName": "קסטינג 200 שחור מעוד",
     "ItemPrice": "34.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קסטינג 200 שחור מעוד",
     "ManufacturerName": "לוריאל",
     "PriceUpdateDate": "2021-01-18 17:06:59",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "34.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3600521094365",
     "AllowDiscount": "1",
     "ItemId": "1011440",
     "ItemName": "קסטינג 300 חום כהה מ",
     "ItemPrice": "34.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קסטינג 300 חום כהה מ",
     "ManufacturerName": "לוריאל",
     "PriceUpdateDate": "2021-01-18 17:06:59",
     "QtyInPackage": "לא ידוע",
     "Quantity": "300.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.1163",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3600521094389",
     "AllowDiscount": "1",
     "ItemId": "1011442",
     "ItemName": "קסטינג 400 חום כהה",
     "ItemPrice": "34.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קסטינג 400 חום כהה",
     "ManufacturerName": "לוריאל",
     "PriceUpdateDate": "2021-01-18 17:06:59",
     "QtyInPackage": "לא ידוע",
     "Quantity": "400.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0872",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018566558",
     "AllowDiscount": "1",
     "ItemId": "6599585",
     "ItemName": "מנצס 150 גר בשקית",
     "ItemPrice": "7.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מנצס 150 גר בשקית",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-09-01 10:31:57",
     "QtyInPackage": "לא ידוע",
     "Quantity": "150.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0527",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3600521720219",
     "AllowDiscount": "1",
     "ItemId": "1011508",
     "ItemName": "דרמו פעולה משולשת לי",
     "ItemPrice": "46.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "דרמו פעולה משולשת לי",
     "ManufacturerName": "לוריאל",
     "PriceUpdateDate": "2023-05-17 11:31:05",
     "QtyInPackage": "לא ידוע",
     "Quantity": "50.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.9380",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290114606547",
     "AllowDiscount": "1",
     "ItemId": "6473711",
     "ItemName": "מיונז עם פטריות כמהי",
     "ItemPrice": "14.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מיונז עם פטריות כמהי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-14 15:16:41",
     "QtyInPackage": "לא ידוע",
     "Quantity": "242.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0612",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3600522022893",
     "AllowDiscount": "1",
     "ItemId": "1011556",
     "ItemName": "אקסלנס קרם 9.3 בלונד",
     "ItemPrice": "36.70",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אקסלנס קרם 9.3 בלונד",
     "ManufacturerName": "לוריאל",
     "PriceUpdateDate": "2023-04-23 11:05:32",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "36.7000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3600522150497",
     "AllowDiscount": "1",
     "ItemId": "1011569",
     "ItemName": "קסטינג 100 שחור עמוק",
     "ItemPrice": "34.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קסטינג 100 שחור עמוק",
     "ManufacturerName": "לוריאל",
     "PriceUpdateDate": "2021-01-18 17:06:59",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "34.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3600522344070",
     "AllowDiscount": "1",
     "ItemId": "1011592",
     "ItemName": "אלביב מסכה קולור פרו",
     "ItemPrice": "24.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אלביב מסכה קולור פרו",
     "ManufacturerName": "אלביב",
     "PriceUpdateDate": "2015-12-20 15:05:21",
     "QtyInPackage": "לא ידוע",
     "Quantity": "300.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0830",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018566572",
     "AllowDiscount": "1",
     "ItemId": "6599586",
     "ItemName": "בוטנים אמריקאיים מצו",
     "ItemPrice": "5.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "בוטנים אמריקאיים מצו",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-12-21 14:24:19",
     "QtyInPackage": "לא ידוע",
     "Quantity": "200.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0295",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018893401",
     "AllowDiscount": "1",
     "ItemId": "6501979",
     "ItemName": "צ'וקטה שוקולד מריר 7",
     "ItemPrice": "8.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "צ'וקטה שוקולד מריר 7",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2021-09-30 17:40:00",
     "QtyInPackage": "לא ידוע",
     "Quantity": "100.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0890",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018443705",
     "AllowDiscount": "1",
     "ItemId": "6642455",
     "ItemName": "לבבות חסה מהדרין",
     "ItemPrice": "10.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "לבבות חסה מהדרין",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-01-15 11:33:45",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "10.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290017617381",
     "AllowDiscount": "1",
     "ItemId": "6639029",
     "ItemName": "סטארקיסט לאנצ בוקס א",
     "ItemPrice": "14.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "סטארקיסט לאנצ בוקס א",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:17:14",
     "QtyInPackage": "לא ידוע",
     "Quantity": "200.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0740",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7777272510010",
     "AllowDiscount": "1",
     "ItemId": "6490154",
     "ItemName": "מדבקות 3D",
     "ItemPrice": "3.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מדבקות 3D",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2021-07-22 09:37:40",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "3.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290019363361",
     "AllowDiscount": "1",
     "ItemId": "6666018",
     "ItemName": "חמאה רמי לוי 200 ג",
     "ItemPrice": "7.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "חמאה רמי לוי 200 ג",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-30 13:37:20",
     "QtyInPackage": "לא ידוע",
     "Quantity": "200.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0390",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290116532899",
     "AllowDiscount": "1",
     "ItemId": "6606465",
     "ItemName": "נשנושים איירביס פלאפ",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "נשנושים איירביס פלאפ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-09-20 11:40:28",
     "QtyInPackage": "לא ידוע",
     "Quantity": "155.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0768",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "5010067322453",
     "AllowDiscount": "1",
     "ItemId": "6552053",
     "ItemName": "טרוביה תחליף אבקת סו",
     "ItemPrice": "34.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "טרוביה תחליף אבקת סו",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:16:44",
     "QtyInPackage": "לא ידוע",
     "Quantity": "280.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.1246",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "859547004084",
     "AllowDiscount": "1",
     "ItemId": "6578903",
     "ItemName": "סקראב דאדי לימון",
     "ItemPrice": "16.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "סקראב דאדי לימון",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-17 15:26:27",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "16.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018792858",
     "AllowDiscount": "1",
     "ItemId": "6575507",
     "ItemName": "קקאו טבעי 500גרם",
     "ItemPrice": "23.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קקאו טבעי 500גרם",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-06-28 14:53:37",
     "QtyInPackage": "לא ידוע",
     "Quantity": "500.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0478",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290012295836",
     "AllowDiscount": "1",
     "ItemId": "6483232",
     "ItemName": "חסה",
     "ItemPrice": "9.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "חסה",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-15 13:28:23",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "9.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290109923130",
     "AllowDiscount": "1",
     "ItemId": "6564344",
     "ItemName": "הפי מדליק פחמים קובי",
     "ItemPrice": "9.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "הפי מדליק פחמים קובי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-05-25 13:45:32",
     "QtyInPackage": "לא ידוע",
     "Quantity": "250.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0392",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "8001841062624",
     "AllowDiscount": "1",
     "ItemId": "6478671",
     "ItemName": "פמפרס מגבונים ללא בי",
     "ItemPrice": "17.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פמפרס מגבונים ללא בי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2021-05-20 11:46:34",
     "QtyInPackage": "לא ידוע",
     "Quantity": "4.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "4.4750",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "4008287058161",
     "AllowDiscount": "1",
     "ItemId": "6467009",
     "ItemName": "קרומבכר בירה בהירה 6",
     "ItemPrice": "34.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קרומבכר בירה בהירה 6",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-26 16:32:56",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.80",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "19.3889",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0",
     "PromotionId": "1305881",
     "PromotionDescription": "קרומבכר פילס בק  מארז שישייה ב29.90 כולל",
     "PromotionUpdateDate": "2023-07-02 00:00",
     "PromotionStartDate": "2023-08-13",
     "PromotionMinQty": "1.00",
     "PromotionDiscountedPrice": "29.90",
     "PromotionDiscountedPricePerMida": "28.10",
     "PromotionMinNoOfItemOfered": "10",
     "PromotionWeightUnit": "1",
     "PromotionDiscountRate": "",
     "PromotionItemCode": [
       "4008287058161"
     ]
   },
   {
     "ItemCode": "7290100704660",
     "AllowDiscount": "1",
     "ItemId": "6475678",
     "ItemName": "סוגת קינואה מיקס 500",
     "ItemPrice": "12.50",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "סוגת קינואה מיקס 500",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2021-05-02 15:31:46",
     "QtyInPackage": "לא ידוע",
     "Quantity": "500.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0250",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290114310536",
     "AllowDiscount": "1",
     "ItemId": "6457748",
     "ItemName": "מולר אקטיב לייט טעם",
     "ItemPrice": "6.20",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מולר אקטיב לייט טעם",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-06 15:37:41",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "6.2000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290002814498",
     "AllowDiscount": "1",
     "ItemId": "6433573",
     "ItemName": "נוזל לניקוי כללי תוס",
     "ItemPrice": "7.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "נוזל לניקוי כללי תוס",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2020-10-11 18:47:26",
     "QtyInPackage": "לא ידוע",
     "Quantity": "750.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0105",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "851621000050",
     "AllowDiscount": "1",
     "ItemId": "6398914",
     "ItemName": "שישיית 1664 בלאנק בק",
     "ItemPrice": "39.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "שישיית 1664 בלאנק בק",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-25 14:14:55",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "39.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0",
     "PromotionId": "1310731",
     "PromotionDescription": "שישיית בירה בלאנק 34.90כולל",
     "PromotionUpdateDate": "2023-08-22 00:00",
     "PromotionStartDate": "2023-08-22",
     "PromotionMinQty": "1.00",
     "PromotionDiscountedPrice": "34.90",
     "PromotionDiscountedPricePerMida": "33.10",
     "PromotionMinNoOfItemOfered": "10",
     "PromotionWeightUnit": "1",
     "PromotionDiscountRate": "",
     "PromotionItemCode": [
       "851621000050"
     ]
   },
   {
     "ItemCode": "693493158657",
     "AllowDiscount": "1",
     "ItemId": "6724823",
     "ItemName": "תפו\"א גורמה",
     "ItemPrice": "6.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "תפו\"א גורמה",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-09-28 11:05:56",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "ק\"ג",
     "UnitOfMeasurePrice": "6.9000",
     "UnitQty": "קילוגרמים",
     "bIsWeighted": "1"
   },
   {
     "ItemCode": "7290113560192",
     "AllowDiscount": "1",
     "ItemId": "6722132",
     "ItemName": "דואלקר 100 מ\"ל",
     "ItemPrice": "24.70",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "דואלקר 100 מ\"ל",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-09-19 12:19:37",
     "QtyInPackage": "לא ידוע",
     "Quantity": "100.00",
     "UnitOfMeasure": "מל",
     "UnitOfMeasurePrice": "0.2470",
     "UnitQty": "מל",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290010650958",
     "AllowDiscount": "1",
     "ItemId": "6695697",
     "ItemName": "פטריות בייבי מלך היע",
     "ItemPrice": "9.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פטריות בייבי מלך היע",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-29 14:02:56",
     "QtyInPackage": "לא ידוע",
     "Quantity": "0.00",
     "UnitOfMeasure": "יחידה   ",
     "UnitOfMeasurePrice": "0.0000",
     "UnitQty": "יחידה   ",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290014935969",
     "AllowDiscount": "1",
     "ItemId": "6718640",
     "ItemName": "שיני שום קלופות 500",
     "ItemPrice": "17.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "שיני שום קלופות 500",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-09-05 16:11:32",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "17.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290102991198",
     "AllowDiscount": "1",
     "ItemId": "6714062",
     "ItemName": "אבקת כביסה מקסימה 3.",
     "ItemPrice": "29.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אבקת כביסה מקסימה 3.",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-08-24 16:15:38",
     "QtyInPackage": "לא ידוע",
     "Quantity": "3.25",
     "UnitOfMeasure": "קג",
     "UnitOfMeasurePrice": "9.2000",
     "UnitQty": "קג",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "8445290510556",
     "AllowDiscount": "1",
     "ItemId": "6686437",
     "ItemName": "נסקפה קפוצ'ינו שיבול",
     "ItemPrice": "18.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "נסקפה קפוצ'ינו שיבול",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-24 14:24:38",
     "QtyInPackage": "לא ידוע",
     "Quantity": "96.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.1969",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "884912418326",
     "AllowDiscount": "1",
     "ItemId": "6703936",
     "ItemName": "קראנצ'ד קוקו פבלס",
     "ItemPrice": "19.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קראנצ'ד קוקו פבלס",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-26 13:39:16",
     "QtyInPackage": "לא ידוע",
     "Quantity": "326.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0610",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290117382943",
     "AllowDiscount": "1",
     "ItemId": "6659661",
     "ItemName": "פוף כוכבים שמנת בצל",
     "ItemPrice": "3.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פוף כוכבים שמנת בצל",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-28 14:36:15",
     "QtyInPackage": "לא ידוע",
     "Quantity": "40.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0975",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "8121300208780",
     "AllowDiscount": "1",
     "ItemId": "6552076",
     "ItemName": "טרוביה תחליף סוכר 36",
     "ItemPrice": "34.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "טרוביה תחליף סוכר 36",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:17:37",
     "QtyInPackage": "לא ידוע",
     "Quantity": "360.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0969",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290003726516",
     "AllowDiscount": "1",
     "ItemId": "6655469",
     "ItemName": "טופו קשה משפחתי 500",
     "ItemPrice": "15.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "טופו קשה משפחתי 500",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-09 15:59:01",
     "QtyInPackage": "לא ידוע",
     "Quantity": "500.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0318",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290108354461",
     "AllowDiscount": "1",
     "ItemId": "6650388",
     "ItemName": "קרליין 10 שמפו חימר",
     "ItemPrice": "10.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קרליין 10 שמפו חימר",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-23 11:42:04",
     "QtyInPackage": "לא ידוע",
     "Quantity": "700.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0156",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290005168475",
     "AllowDiscount": "1",
     "ItemId": "6550301",
     "ItemName": "תירוש אדום מובחר 100",
     "ItemPrice": "16.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "תירוש אדום מובחר 100",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-04-11 08:55:31",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "16.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018566619",
     "AllowDiscount": "1",
     "ItemId": "6593788",
     "ItemName": "פסטה פנה",
     "ItemPrice": "3.40",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פסטה פנה",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-19 14:04:19",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "3.4000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "818159017493",
     "AllowDiscount": "1",
     "ItemId": "6641518",
     "ItemName": "ממחטות כיס 8יח BERRA",
     "ItemPrice": "4.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "ממחטות כיס 8יח BERRA",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-01-12 12:01:12",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "4.8000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290017947464",
     "AllowDiscount": "1",
     "ItemId": "6530130",
     "ItemName": "אנגל פיתות כוסמין 8י",
     "ItemPrice": "15.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אנגל פיתות כוסמין 8י",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:12:50",
     "QtyInPackage": "לא ידוע",
     "Quantity": "400.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0398",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290110558925",
     "AllowDiscount": "1",
     "ItemId": "6637053",
     "ItemName": "לקט מיקס אורגולה  צב",
     "ItemPrice": "10.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "לקט מיקס אורגולה  צב",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-01-01 12:56:40",
     "QtyInPackage": "לא ידוע",
     "Quantity": "300.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0363",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "8001090832610",
     "AllowDiscount": "1",
     "ItemId": "6397578",
     "ItemName": "פנטן שמפו למגע רך כמ",
     "ItemPrice": "18.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פנטן שמפו למגע רך כמ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2020-05-11 09:58:35",
     "QtyInPackage": "לא ידוע",
     "Quantity": "660.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0286",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290116053462",
     "AllowDiscount": "1",
     "ItemId": "6590957",
     "ItemName": "ידית סיליקון לסירים",
     "ItemPrice": "9.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "ידית סיליקון לסירים",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-08-09 15:32:43",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "9.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7613287476494",
     "AllowDiscount": "1",
     "ItemId": "6491886",
     "ItemName": "אסם רוטב מיונז לחיץ",
     "ItemPrice": "12.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אסם רוטב מיונז לחיץ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:17:35",
     "QtyInPackage": "לא ידוע",
     "Quantity": "280.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0457",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290116532905",
     "AllowDiscount": "1",
     "ItemId": "6606466",
     "ItemName": "נשנושים איירביס ברבי",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "נשנושים איירביס ברבי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-09-20 11:40:28",
     "QtyInPackage": "לא ידוע",
     "Quantity": "155.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0768",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018294192",
     "AllowDiscount": "1",
     "ItemId": "6510279",
     "ItemName": "פרייבט קולקשין בלנד",
     "ItemPrice": "38.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פרייבט קולקשין בלנד",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-26 16:32:56",
     "QtyInPackage": "לא ידוע",
     "Quantity": "700.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0556",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290019056942",
     "AllowDiscount": "1",
     "ItemId": "6722394",
     "ItemName": "מים עין גדי 2 ליטר",
     "ItemPrice": "2.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מים עין גדי 2 ליטר",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-09-19 14:51:37",
     "QtyInPackage": "לא ידוע",
     "Quantity": "2000.00",
     "UnitOfMeasure": "100 מ'ל",
     "UnitOfMeasurePrice": "0.0014",
     "UnitQty": "מטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290110554613",
     "AllowDiscount": "1",
     "ItemId": "6702048",
     "ItemName": "חטיף קוואקר וניל 50",
     "ItemPrice": "3.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "חטיף קוואקר וניל 50",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-23 10:27:30",
     "QtyInPackage": "לא ידוע",
     "Quantity": "0.00",
     "UnitOfMeasure": "יחידה   ",
     "UnitOfMeasurePrice": "0.0000",
     "UnitQty": "יחידה   ",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290116533711",
     "AllowDiscount": "1",
     "ItemId": "6688013",
     "ItemName": "רקסונה  ספריי 150 נש",
     "ItemPrice": "13.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "רקסונה  ספריי 150 נש",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-01 10:41:28",
     "QtyInPackage": "לא ידוע",
     "Quantity": "150.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0927",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290112199133",
     "AllowDiscount": "1",
     "ItemId": "6639458",
     "ItemName": "ניוקי תפוא ללא גלוטן",
     "ItemPrice": "13.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "ניוקי תפוא ללא גלוטן",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-03 09:03:00",
     "QtyInPackage": "לא ידוע",
     "Quantity": "500.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0278",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290014935976",
     "AllowDiscount": "1",
     "ItemId": "6718641",
     "ItemName": "שיני שום קלופות 1 קג",
     "ItemPrice": "29.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "שיני שום קלופות 1 קג",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-09-05 16:11:32",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "29.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "5904941751975",
     "AllowDiscount": "1",
     "ItemId": "6509119",
     "ItemName": "בלו משקה אנרגיה דיי",
     "ItemPrice": "3.50",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "בלו משקה אנרגיה דיי",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-12 20:09:31",
     "QtyInPackage": "לא ידוע",
     "Quantity": "250.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0140",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290019075387",
     "AllowDiscount": "1",
     "ItemId": "6685533",
     "ItemName": "אפקטיב קר תרחיץ פנים",
     "ItemPrice": "16.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אפקטיב קר תרחיץ פנים",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-23 11:33:38",
     "QtyInPackage": "לא ידוע",
     "Quantity": "180.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0933",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "8718951419179",
     "AllowDiscount": "1",
     "ItemId": "6659662",
     "ItemName": "פלמוליב סבון ידיים ס",
     "ItemPrice": "10.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פלמוליב סבון ידיים ס",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-03-02 10:14:27",
     "QtyInPackage": "לא ידוע",
     "Quantity": "300.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0363",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "598288956329",
     "AllowDiscount": "1",
     "ItemId": "6695698",
     "ItemName": "מנשפי נייר זהב-כסף פ",
     "ItemPrice": "8.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מנשפי נייר זהב-כסף פ",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-29 14:03:14",
     "QtyInPackage": "לא ידוע",
     "Quantity": "0.00",
     "UnitOfMeasure": "יחידה   ",
     "UnitOfMeasurePrice": "0.0000",
     "UnitQty": "יחידה   ",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290110552909",
     "AllowDiscount": "1",
     "ItemId": "6694332",
     "ItemName": "כיף כף חצי חצי שוקו",
     "ItemPrice": "3.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "כיף כף חצי חצי שוקו",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-06-25 15:39:02",
     "QtyInPackage": "לא ידוע",
     "Quantity": "45.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0867",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290110115371",
     "AllowDiscount": "1",
     "ItemId": "6507981",
     "ItemName": "קוקה קולה דייט 6*1.5",
     "ItemPrice": "40.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קוקה קולה דייט 6*1.5",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-05-28 10:28:11",
     "QtyInPackage": "לא ידוע",
     "Quantity": "9.00",
     "UnitOfMeasure": "ליטר    ",
     "UnitOfMeasurePrice": "4.5444",
     "UnitQty": "ליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018386767",
     "AllowDiscount": "1",
     "ItemId": "6679012",
     "ItemName": "טפטפים בייביסקין קרם",
     "ItemPrice": "11.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "טפטפים בייביסקין קרם",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-30 09:49:00",
     "QtyInPackage": "לא ידוע",
     "Quantity": "100.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.1190",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "8001090318367",
     "AllowDiscount": "1",
     "ItemId": "6678316",
     "ItemName": "אריאל קפסולות 45 יח",
     "ItemPrice": "64.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אריאל קפסולות 45 יח",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-25 09:50:13",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "64.9000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018566626",
     "AllowDiscount": "1",
     "ItemId": "6593789",
     "ItemName": "פסטה פוזילי חיטה מלא",
     "ItemPrice": "3.40",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "פסטה פוזילי חיטה מלא",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-04-19 14:04:19",
     "QtyInPackage": "לא ידוע",
     "Quantity": "1.00",
     "UnitOfMeasure": "יח'",
     "UnitOfMeasurePrice": "3.4000",
     "UnitQty": "יח'",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290019074090",
     "AllowDiscount": "1",
     "ItemId": "6582960",
     "ItemName": "קמיל בלו אקסטרה סופט",
     "ItemPrice": "22.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קמיל בלו אקסטרה סופט",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-07-20 08:07:32",
     "QtyInPackage": "לא ידוע",
     "Quantity": "500.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0458",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "3800124221612",
     "AllowDiscount": "1",
     "ItemId": "6697049",
     "ItemName": "סאני מיקס 2קג לחתול",
     "ItemPrice": "49.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "סאני מיקס 2קג לחתול",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-06 10:24:01",
     "QtyInPackage": "לא ידוע",
     "Quantity": "0.00",
     "UnitOfMeasure": "יחידה   ",
     "UnitOfMeasurePrice": "0.0000",
     "UnitQty": "יחידה   ",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290108354478",
     "AllowDiscount": "1",
     "ItemId": "6650389",
     "ItemName": "קרליין 10 מרכך חימר",
     "ItemPrice": "10.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "קרליין 10 מרכך חימר",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-23 11:42:04",
     "QtyInPackage": "לא ידוע",
     "Quantity": "700.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0156",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290108356717",
     "AllowDiscount": "1",
     "ItemId": "6634567",
     "ItemName": "כיף מן 3 ב 1 מעושר ב",
     "ItemPrice": "9.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "כיף מן 3 ב 1 מעושר ב",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-12-22 15:49:40",
     "QtyInPackage": "לא ידוע",
     "Quantity": "700.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0141",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018468302",
     "AllowDiscount": "1",
     "ItemId": "6558621",
     "ItemName": "נקניקיה צמחית סגנון",
     "ItemPrice": "39.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "נקניקיה צמחית סגנון",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-07-23 15:03:28",
     "QtyInPackage": "לא ידוע",
     "Quantity": "400.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0997",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290011644000",
     "AllowDiscount": "1",
     "ItemId": "6628817",
     "ItemName": "מקלות תירס ממותקים 6",
     "ItemPrice": "4.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "מקלות תירס ממותקים 6",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2022-12-08 13:55:35",
     "QtyInPackage": "לא ידוע",
     "Quantity": "60.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0817",
     "UnitQty": "גרמים",
     "bIsWeighted": "0",
     "PromotionId": "1295518",
     "PromotionDescription": "חטיף מקלות תירס 3ב12",
     "PromotionUpdateDate": "2023-04-18 00:00",
     "PromotionStartDate": "2023-03-16",
     "PromotionMinQty": "3.00",
     "PromotionDiscountedPrice": "12.00",
     "PromotionDiscountedPricePerMida": "4.00",
     "PromotionMinNoOfItemOfered": "10",
     "PromotionWeightUnit": "1",
     "PromotionDiscountRate": "",
     "PromotionItemCode": [
       "7290011644000"
     ]
   },
   {
     "ItemCode": "8006540212530",
     "AllowDiscount": "1",
     "ItemId": "6671386",
     "ItemName": "הרבל אסנסס שמפו מנוק",
     "ItemPrice": "13.90",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "הרבל אסנסס שמפו מנוק",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-03-30 10:03:15",
     "QtyInPackage": "לא ידוע",
     "Quantity": "400.00",
     "UnitOfMeasure": "100 מ\"ל",
     "UnitOfMeasurePrice": "0.0348",
     "UnitQty": "מיליליטרים",
     "bIsWeighted": "0"
   },
   {
     "ItemCode": "7290018792810",
     "AllowDiscount": "1",
     "ItemId": "6651828",
     "ItemName": "אבקת שוקליקו  420 ג",
     "ItemPrice": "11.80",
     "ItemStatus": "1",
     "ItemType": "1",
     "ManufactureCountry": "לא ידוע",
     "ManufacturerItemDescription": "אבקת שוקליקו  420 ג",
     "ManufacturerName": "לא ידוע",
     "PriceUpdateDate": "2023-02-07 11:00:34",
     "QtyInPackage": "לא ידוע",
     "Quantity": "420.00",
     "UnitOfMeasure": "100 גרם",
     "UnitOfMeasurePrice": "0.0281",
     "UnitQty": "גרמים",
     "bIsWeighted": "0"
   }
 ]